apiVersion: apps/v1
kind: Deployment
metadata:
  name: teachme-app
spec:
  selector:
    matchLabels:
      app: teachme-app
  replicas: 1
  template:
    metadata:
      labels:
        app: teachme-app
    spec:
      containers:
      - name: teachme-app
        image: mrlionbyte/teachmeapp:latest
        ports:
        - containerPort: 8000  
        env:
        - name: DATABASE_NAME
          value: "db_teachme"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "0483"
        - name: DATABASE_HOST
          value: "postgres"  
        - name: DATABASE_PORT
          value: "5432"     
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"] 

---
apiVersion: v1
kind: Service
metadata:
  name: teachme-app
spec:
  type: NodePort
  ports:
    - port: 8000         
      targetPort: 8000   
      nodePort: 30027   
  selector:
    app: teachme-app
