version: '3.8'

services:
  teachme_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: 0483  
      POSTGRES_DB: db_teachme    
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  teachmeapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: teachme_postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 0483
      DATABASE_NAME: db_teachme
    depends_on:
      - teachme_postgres
    ports:
      - "8099:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
