name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 0483
          POSTGRES_DB: db_teachme
        ports:
          - "5442:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and run services
        run: |
          docker compose up -d --build

      - name: Wait for the service to be ready
        run: |
          docker compose exec -T teachmeapp bash -c 'while ! pg_isready -h teachme_postgres -p 5432; do sleep 1; done'

      - name: Run tests
        run: |
          docker compose exec -T teachmeapp pytest

      - name: Shut down services
        run: docker compose down
