name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 0483
          POSTGRES_DB: db_teachme
        ports:
          - "5442:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Clean up any existing containers
        run: |
          docker-compose down || true
          docker system prune -f

      - name: Build and run services
        run: |
          for i in {1..3}; do
            docker-compose up -d --build && break || sleep 10;
          done

      - name: Wait for the service to be ready
        run: |
          docker-compose exec -T teachmeapp bash -c 'while ! pg_isready -h teachme_postgres -p 5432; do sleep 1; done'

      - name: Check container status
        run: docker-compose ps

      - name: View container logs
        run: docker-compose logs teachmeapp

      - name: Run tests
        run: |
          docker-compose exec -T teachmeapp pytest

      - name: Shut down services
        run: docker-compose down
