name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 0483
          POSTGRES_DB: db_teachme
        ports:
          - "0:5432"

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Clean up any existing containers
        run: |
          docker-compose down || true
          docker system prune -f

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and run services
        run: |
          for i in {1..3}; do
            docker-compose up -d --build && break || sleep 10;
          done

      - name: Run tests
        run: |
          docker-compose exec teachmeapp pytest

      - name: Shut down services
        run: docker-compose down
